[tool.poetry]
name = "covid19-cases-switzerland"
version = "0.1.0"
description = ""
authors = ["Daniel Probst"]

[tool.poetry.dependencies]
python = ">=3.6.1"
pandas = "^1.0.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
